### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by nuevocs** [MatthewCaseres/programmable-pomodoro#1]
Hi!

Would you please advise how to fix this error?

--->

Traceback (most recent call last):
File "/Users/xxxPython/Apps/simple_pomodoro/main.py", line 4, in
from programmable_pomodoro import Pomodoro
File "/Users/xxxPython/Apps/simple_pomodoro/programmable_pomodoro/init.py", line 13, in
with importlib.resources.path(audio, "alarm.wav") as alarmPath:
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 165, in path
_common.as_file(files(package).joinpath(_normalize_path(resource)))
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/resources.py", line 147, in files
return _common.from_package(_get_package(package))
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_common.py", line 14, in from_package
return fallback_resources(package.spec)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/_common.py", line 18, in fallback_resources
package_directory = pathlib.Path(spec.origin).parent
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 1071, in new
self = cls._from_parts(args, init=False)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 696, in _from_parts
drv, root, parts = self._parse_args(args)
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/pathlib.py", line 680, in _parse_args
a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType

**Comment by MatthewCaseres** [comment]
yeah this might be on me, let me check it out

**Comment by MatthewCaseres** [comment]
Easiest fix is to clone the repo and see if it runs locally?

Having issues with the audio library, might have to scrap the audio but I don't want to. This is a bug.

**Comment by nuevocs** [comment]
tried to run the clone in local, but got the same error..

**Comment by MatthewCaseres** [comment]
Ok, I am having problems with the audio library. I just put version 0.1.1 which removes the audio but will resolve the error. You can install on pip or clone locally, I just tested pip install and it seemed to work fine.

See #2 for the inclusion of a ringing bell.

**Comment by MatthewCaseres** [comment]
I was able to run this in a container so I think it works on machines that aren't just mine now, despite losing sound.
